<?php

/*********************************************************************
* Extension configuration file for ext "static_info_tables_fr".
*
* Generated by ext 17-11-2015 16:53 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Static Info Tables (fr)',
  'description' => 'French (fr) language pack for the Static Info Tables providing localized names for countries, currencies and so on.',
  'category' => 'misc',
  'shy' => 0,
  'version' => '6.1.0',
  'priority' => '',
  'loadOrder' => '',
  'module' => '',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearcacheonload' => 1,
  'lockType' => '',
  'author' => 'Francois Suter',
  'author_email' => 'typo3@cobweb.ch',
  'author_company' => 'Cobweb',
  'CGLcompliance' => '',
  'CGLcompliance_note' => '',
  'constraints' => 
  array (
    'depends' => 
    array (
      'static_info_tables' => '6.3.4-0.0.0',
      'typo3' => '6.2.0-7.9.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  '_md5_values_when_last_written' => '',
  'comment' => 'Verified compatibility with TYPO3 CMS 7; updated for recent versions of static_info_tables.',
  'user' => 'francois',
);

?>