<?php

/*********************************************************************
 * Extension configuration file for ext "static_info_tables_fr".
 *
 * Generated by ext 17-11-2015 16:53 UTC
 *
 * https://github.com/t3elmar/Ext
 *********************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Static Info Tables (fr)',
    'description' => 'French (fr) language pack for the Static Info Tables providing localized names for countries, currencies and so on.',
    'category' => 'misc',
    'shy' => 0,
    'version' => '6.1.0',
    'priority' => '',
    'loadOrder' => '',
    'module' => '',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'modify_tables' => '',
    'clearcacheonload' => 1,
    'lockType' => '',
    'author' => 'Manuel Selbach',
    'author_email' => 'manuel_selbach@yahoo.de',
    'author_company' => 'Cobweb',
    'CGLcompliance' => '',
    'CGLcompliance_note' => '',
    'constraints' => [
        'depends' => [
            'static_info_tables' => '6.3.4-0.0.0',
            'typo3' => '6.2.0-7.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    '_md5_values_when_last_written' => '',
    'comment' => 'Verified compatibility with TYPO3 CMS 7; updated for recent versions of static_info_tables.',
    'user' => 'francois',
];
