## static_territories
UPDATE static_territories SET tr_name_fr='Afrique' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_fr='Océanie' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_fr='Amériques' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_fr='Asie' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_fr='Europe' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_fr='Asie orientale' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_fr='Asie du Sud-Est' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_fr='Asie centrale' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_fr='Asie occidentale' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_fr='Europe méridionale' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_fr='Europe orientale' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_fr='Europe septentrionale' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_fr='Europe occidentale' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_fr='Amérique du Sud' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_fr='Amérique centrale' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_fr='Amérique du Nord' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_fr='Caraïbes' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_fr='Afrique occidentale' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_fr='Afrique orientale' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_fr='Afrique septentrionale' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_fr='Afrique centrale' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_fr='Afrique australe' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_fr='Australie et Nouvelle-Zélande' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_fr='Mélanésie' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_fr='Micronésie' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_fr='Polynésie' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_fr='Asie méridionale' WHERE tr_iso_nr='34';


## static_countries
UPDATE static_countries SET cn_short_fr='Andorre' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_fr='Émirats arabes unis' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_fr='Afghanistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_fr='Antigua-et-Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_fr='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_fr='Albanie' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_fr='Arménie' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_fr='Antilles néerlandaises' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_fr='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_fr='Antarctique' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_fr='Argentine' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_fr='Samoa américaines' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_fr='Autriche' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_fr='Australie' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_fr='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_fr='Azerbaïdjan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_fr='Bosnie-Herzégovine' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_fr='Barbade' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_fr='Bangladesh' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_fr='Belgique' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_fr='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_fr='Bulgarie' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_fr='Bahreïn' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_fr='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_fr='Bénin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_fr='Bermudes' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_fr='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_fr='Bolivie' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_fr='Brésil' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_fr='Les Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_fr='Bhoutan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_fr='Île Bouvet' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_fr='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_fr='Bélarus' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_fr='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_fr='Canada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_fr='Îles Cocos (Keeling)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_fr='Congo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_fr='Centrafrique' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_fr='Congo-Brazzaville' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_fr='Suisse' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_fr='Côte d’Ivoire' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_fr='Îles Cook' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_fr='Chili' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_fr='Cameroun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_fr='Chine' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_fr='Colombie' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_fr='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_fr='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_fr='Cap-Vert' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_fr='Île Christmas' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_fr='Chypre' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_fr='République tchèque' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_fr='Allemagne' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_fr='Djibouti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_fr='Danemark' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_fr='Dominique' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_fr='République dominicaine' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_fr='Algérie' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_fr='Équateur' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_fr='Estonie' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_fr='Égypte' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_fr='Sahara occidental' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_fr='Érythrée' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_fr='Espagne' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_fr='Éthiopie' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_fr='Finlande' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_fr='Fidji' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_fr='Îles Malouines' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_fr='Micronésie' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_fr='Îles Féroé' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_fr='France' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_fr='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_fr='Royaume-Uni' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_fr='Grenade' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_fr='Géorgie' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_fr='Guyane française' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_fr='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_fr='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_fr='Groenland' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_fr='Gambie' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_fr='Guinée' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_fr='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_fr='Guinée équatoriale' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_fr='Grèce' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_fr='Géorgie du Sud et les Îles Sandwich du Sud' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_fr='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_fr='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_fr='Guinée-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_fr='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_fr='Hong Kong RAS de Chine' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_fr='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_fr='Croatie' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_fr='Haïti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_fr='Hongrie' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_fr='Indonésie' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_fr='Irlande' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_fr='Israël' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_fr='Inde' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_fr='Territoire britannique de l’océan indien' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_fr='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_fr='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_fr='Islande' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_fr='Italie' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_fr='Jamaïque' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_fr='Jordanie' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_fr='Japon' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_fr='Kenya' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_fr='Kirghizistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_fr='Cambodge' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_fr='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_fr='Comores' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_fr='Saint-Kitts-et-Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_fr='Corée du Nord' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_fr='Corée du Sud' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_fr='Koweït' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_fr='Îles Caïmanes' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_fr='Kazakhstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_fr='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_fr='Liban' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_fr='Sainte-Lucie' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_fr='Liechtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_fr='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_fr='Libéria' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_fr='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_fr='Lituanie' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_fr='Luxembourg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_fr='Lettonie' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_fr='Libye' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_fr='Maroc' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_fr='Monaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_fr='Moldavie' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_fr='Madagascar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_fr='Îles Marshall' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_fr='Macédoine' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_fr='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_fr='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_fr='Mongolie' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_fr='Macao RAS de Chine' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_fr='Îles Mariannes du Nord' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_fr='Martinique' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_fr='Mauritanie' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_fr='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_fr='Malte' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_fr='Maurice' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_fr='Maldives' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_fr='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_fr='Mexique' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_fr='Malaisie' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_fr='Mozambique' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_fr='Namibie' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_fr='Nouvelle-Calédonie' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_fr='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_fr='Île Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_fr='Nigéria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_fr='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_fr='Pays-Bas' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_fr='Norvège' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_fr='Népal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_fr='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_fr='Niué' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_fr='Nouvelle-Zélande' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_fr='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_fr='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_fr='Pérou' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_fr='Polynésie française' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_fr='Papouasie-Nouvelle-Guinée' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_fr='Philippines' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_fr='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_fr='Pologne' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_fr='Saint-Pierre-et-Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_fr='Îles Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_fr='Porto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_fr='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_fr='Palaos' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_fr='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_fr='Qatar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_fr='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_fr='Roumanie' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_fr='Russie' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_fr='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_fr='Arabie saoudite' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_fr='Îles Salomon' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_fr='Seychelles' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_fr='Soudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_fr='Suède' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_fr='Singapour' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_fr='Sainte-Hélène' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_fr='Slovénie' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_fr='Svalbard' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_fr='Slovaquie' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_fr='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_fr='Saint-Marin' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_fr='Sénégal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_fr='Somalie' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_fr='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_fr='Sao Tomé-et-Principe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_fr='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_fr='Syrie' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_fr='Swaziland' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_fr='Îles Turks et Caïques' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_fr='Tchad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_fr='Terres australes françaises' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_fr='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_fr='Thaïlande' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_fr='Tadjikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_fr='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_fr='Turkménistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_fr='Tunisie' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_fr='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_fr='Timor-Leste' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_fr='Turquie' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_fr='Trinité-et-Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_fr='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_fr='Taïwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_fr='Tanzanie' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_fr='Ukraine' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_fr='Ouganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_fr='Îles Mineures Éloignées des États-Unis' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_fr='États-Unis' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_fr='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_fr='Ouzbékistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_fr='Cité du Vatican' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_fr='Saint-Vincent-et-les Grenadines' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_fr='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_fr='Îles Vierges Britanniques' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_fr='Îles Vierges des États-Unis' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_fr='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_fr='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_fr='Wallis-et-Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_fr='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_fr='Yémen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_fr='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_fr='Afrique du Sud' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_fr='Zambie' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_fr='Zimbabwe' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_fr='Palestine' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_fr='Serbie-et-Monténégro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_fr='Îles d’Åland' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_fr='Île Heard et les Îles McDonald' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_fr='Monténégro' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_fr='Serbie' WHERE cn_iso_2='RS';

## static_country_zones
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='AK';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='AZ';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='DE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='DC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='FL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='GA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='GU';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='HI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='ID';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='IL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='IN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='IA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='KS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='KY';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='LA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='MD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='NV';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='NH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='NJ';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='NM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='NY';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='NC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='ND';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='OH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='OK';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='SD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='TX';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='UT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='WV';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='US' AND zn_code='WY';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='CA' AND zn_code='AB';
UPDATE static_country_zones SET zn_name_fr='Colombie-britannique' WHERE zn_country_iso_2='CA' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='CA' AND zn_code='MB';
UPDATE static_country_zones SET zn_name_fr='Terre-Neuve-et-Labrador' WHERE zn_country_iso_2='CA' AND zn_code='NF';
UPDATE static_country_zones SET zn_name_fr='Nouveau-Brunswick' WHERE zn_country_iso_2='CA' AND zn_code='NB';
UPDATE static_country_zones SET zn_name_fr='Nouvelle-Écosse' WHERE zn_country_iso_2='CA' AND zn_code='NS';
UPDATE static_country_zones SET zn_name_fr='Territoires-du-Nord-Ouest' WHERE zn_country_iso_2='CA' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='CA' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='CA' AND zn_code='ON';
UPDATE static_country_zones SET zn_name_fr='Île-du-Prince-Édouard' WHERE zn_country_iso_2='CA' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='CA' AND zn_code='QC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='CA' AND zn_code='SK';
UPDATE static_country_zones SET zn_name_fr='Yukon' WHERE zn_country_iso_2='CA' AND zn_code='YT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='NDS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='BAW';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='BAY';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='BER';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='BRG';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='BRE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='HAM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='HES';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='MEC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='NRW';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='RHE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='SAR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='SAS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='SAC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='SCN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='DE' AND zn_code='THE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AT' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AT' AND zn_code='OO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AT' AND zn_code='SB';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AT' AND zn_code='KN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AT' AND zn_code='ST';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AT' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AT' AND zn_code='VB';
UPDATE static_country_zones SET zn_name_fr='Argovie' WHERE zn_country_iso_2='CH' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_fr='Appenzell Rhodes-Intérieures' WHERE zn_country_iso_2='CH' AND zn_code='AI';
UPDATE static_country_zones SET zn_name_fr='Appenzell Rhodes-Extérieures' WHERE zn_country_iso_2='CH' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_fr='Berne' WHERE zn_country_iso_2='CH' AND zn_code='BE';
UPDATE static_country_zones SET zn_name_fr='Bâle-Campagne' WHERE zn_country_iso_2='CH' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_fr='Bâle-Ville' WHERE zn_country_iso_2='CH' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_fr='Fribourg' WHERE zn_country_iso_2='CH' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_fr='Genève' WHERE zn_country_iso_2='CH' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_fr='Glaris' WHERE zn_country_iso_2='CH' AND zn_code='GL';
UPDATE static_country_zones SET zn_name_fr='Grisons' WHERE zn_country_iso_2='CH' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_fr='Jura' WHERE zn_country_iso_2='CH' AND zn_code='JU';
UPDATE static_country_zones SET zn_name_fr='Lucerne' WHERE zn_country_iso_2='CH' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_fr='Neuchâtel' WHERE zn_country_iso_2='CH' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_fr='Nidwald' WHERE zn_country_iso_2='CH' AND zn_code='NW';
UPDATE static_country_zones SET zn_name_fr='Obwald' WHERE zn_country_iso_2='CH' AND zn_code='OW';
UPDATE static_country_zones SET zn_name_fr='Saint-Gall' WHERE zn_country_iso_2='CH' AND zn_code='SG';
UPDATE static_country_zones SET zn_name_fr='Schaffouse' WHERE zn_country_iso_2='CH' AND zn_code='SH';
UPDATE static_country_zones SET zn_name_fr='Soleure' WHERE zn_country_iso_2='CH' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_fr='Schwyz' WHERE zn_country_iso_2='CH' AND zn_code='SZ';
UPDATE static_country_zones SET zn_name_fr='Thurgovie' WHERE zn_country_iso_2='CH' AND zn_code='TG';
UPDATE static_country_zones SET zn_name_fr='Tessin' WHERE zn_country_iso_2='CH' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_fr='Uri' WHERE zn_country_iso_2='CH' AND zn_code='UR';
UPDATE static_country_zones SET zn_name_fr='Vaud' WHERE zn_country_iso_2='CH' AND zn_code='VD';
UPDATE static_country_zones SET zn_name_fr='Valais' WHERE zn_country_iso_2='CH' AND zn_code='VS';
UPDATE static_country_zones SET zn_name_fr='Zoug' WHERE zn_country_iso_2='CH' AND zn_code='ZG';
UPDATE static_country_zones SET zn_name_fr='Zurich' WHERE zn_country_iso_2='CH' AND zn_code='ZH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Alava';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Malaga';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Segovia';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Granada';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Jaen';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Sevilla';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Barcelona';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Valencia';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Alicante';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Almeria';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Asturias';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Avila';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Badajoz';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Burgos';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Caceres';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Cadiz';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Cantabria';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Castellon';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Ceuta';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Ciudad Real';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Cordoba';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Cuenca';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Girona';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Las Palmas';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Guadalajara';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Guipuzcoa';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Huelva';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Huesca';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='A Coruña';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='La Rioja';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Leon';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Lugo';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Lleida';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Madrid';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Baleares';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Murcia';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Navarra';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Ourense';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Palencia';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Pontevedra';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Salamanca';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Soria';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Tarragona';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Tenerife';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Teruel';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Toledo';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Valladolid';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Vizcaya';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Zamora';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Zaragoza';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='ES' AND zn_code='Melilla';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='AGS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='BCS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='CAM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='CHIS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='CHIH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='COAH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='COL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='DIF';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='DGO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='GTO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='GRO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='HGO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='JAL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='MEX';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='MICH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='MOR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='NAY';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='NL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='OAX';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='PUE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='QRO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='QROO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='SLP';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='SIN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='SON';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='TAB';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='TAMPS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='TLAX';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='VER';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='YUC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='MX' AND zn_code='ZAC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AU' AND zn_code='ACT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AU' AND zn_code='NSW';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AU' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AU' AND zn_code='QLD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AU' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AU' AND zn_code='TAS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AU' AND zn_code='VIC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='AU' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='AN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='AO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='AQ';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='AT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='AV';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='BG';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='BI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='BN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='BO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='BR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='BZ';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CB';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='CZ';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='EN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='FE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='FG';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='FI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='FO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='IM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='IS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='KR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='LC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='LE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='LI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='LO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='LT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='MC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='NA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PG';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PV';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='PZ';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='RA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='RC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='RE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='RG';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='RM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='SI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='SR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='SS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='SV';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='TA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='TE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='TO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='TP';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='TR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='TS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='TV';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='UD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='VC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='VE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='VI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='VP';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='VR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IT' AND zn_code='VV';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='ALD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='ARM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='ATM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='BDS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='BFD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='BIR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='BLG';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='BRI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='BRK';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='BRS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='BUX';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CAP';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CAS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CBA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CBE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CER';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CHI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CHS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CLD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CNL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CON';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CTR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='CVE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='DEN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='DFD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='DGL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='DHM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='DOR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='DVN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='DWN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='DYS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='ESX';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='FER';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='FFE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='FLI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='FMH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='GDD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='GLO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='GLR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='GNM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='GNS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='GNW';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='GRN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='GUR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='GWT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='HBS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='HFD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='HLD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='HPH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='HWR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='IOM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='IOW';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='ISL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='JER';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='KNT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='LCN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='LDN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='LDR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='LEC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='LNH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='LTE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='LTM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='LTW';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='MCH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='MER';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='MSY';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='NET';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='NEW';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='NHM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='NLD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='NOR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='NOT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='NWH';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='OFE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='ORK';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='PEM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='PWS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SCD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SFD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SFK';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SLD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SOM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SPE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SRK';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SRY';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SWA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SXE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='SXW';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='TAF';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='TOR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='TWR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='TYR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='TYS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='VAL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='WIL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='WKS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='WLT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='WMD';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='WRE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='YSN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='YSS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='GB' AND zn_code='YSW';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='CAV';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='CLA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='COR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='DON';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='DUB';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='GAL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='KER';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='KIL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='KLK';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='LAO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='LEI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='LIM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='LOU';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='MAY';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='MEA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='OFF';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='ROS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='SLI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='TIP';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='WAT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='WES';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='WEX';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='IE' AND zn_code='WIC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='AC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='AM';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='DF';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='ES';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='MG';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='PB';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='RJ';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='RR';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='RS';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='SE';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_fr='' WHERE zn_country_iso_2='BR' AND zn_code='TO';


## static_currencies
UPDATE static_currencies SET cu_name_fr='Dirham des Émirats arabes unis',cu_sub_name_fr='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_fr='Lek albanais',cu_sub_name_fr='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_fr='Dram arménien',cu_sub_name_fr='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_fr='Florin des Antilles néerlandaises',cu_sub_name_fr='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_fr='Kwanza angolais',cu_sub_name_fr='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_fr='Peso argentin',cu_sub_name_fr='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_fr='Dollar australien',cu_sub_name_fr='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_fr='Florin d’Aruba',cu_sub_name_fr='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_fr='Manat azéri',cu_sub_name_fr='' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_fr='Mark convertible de Bosnie-Herzegovine',cu_sub_name_fr='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_fr='Dollar de Barbade',cu_sub_name_fr='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_fr='Taka bengali',cu_sub_name_fr='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_fr='Lev bulgare',cu_sub_name_fr='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_fr='Dinar de Bahrein',cu_sub_name_fr='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_fr='Franc burundais',cu_sub_name_fr='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_fr='Dollar des Bermudes',cu_sub_name_fr='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_fr='Dollar de Brunei',cu_sub_name_fr='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_fr='Boliviano',cu_sub_name_fr='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_fr='Réal',cu_sub_name_fr='centime' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_fr='Dollar des Bahamas',cu_sub_name_fr='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_fr='Ngultrum bhoutanais',cu_sub_name_fr='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_fr='Pula botswanais',cu_sub_name_fr='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_fr='Rouble biélorusse',cu_sub_name_fr='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_fr='Dollar de Bélize',cu_sub_name_fr='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_fr='Dollar canadien',cu_sub_name_fr='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_fr='Franc congolais',cu_sub_name_fr='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_fr='Franc suisse',cu_sub_name_fr='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_fr='Peso chilien',cu_sub_name_fr='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_fr='Yuan Renminbi',cu_sub_name_fr='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_fr='Peso colombien',cu_sub_name_fr='centime' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_fr='Colon costaricain',cu_sub_name_fr='centime' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_fr='Peso cubain',cu_sub_name_fr='centime' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_fr='Escudo capverdien',cu_sub_name_fr='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_fr='Livre chypriote',cu_sub_name_fr='' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_fr='Couronne tchèque',cu_sub_name_fr='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_fr='Franc Djibouti',cu_sub_name_fr='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_fr='Couronne danoise',cu_sub_name_fr='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_fr='Peso dominicain',cu_sub_name_fr='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_fr='Dinar algérien',cu_sub_name_fr='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_fr='Couronne estonienne',cu_sub_name_fr='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_fr='Livre égyptienne',cu_sub_name_fr='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_fr='Nakfa érythréen',cu_sub_name_fr='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_fr='Birr éthiopien',cu_sub_name_fr='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_fr='Euro',cu_sub_name_fr='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_fr='Dollar fidjien',cu_sub_name_fr='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_fr='Livre des Îles Malouines',cu_sub_name_fr='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_fr='Livre sterling',cu_sub_name_fr='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_fr='Lari géorgien',cu_sub_name_fr='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_fr='Cedi ghanéen',cu_sub_name_fr='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_fr='Livre de Gibraltar',cu_sub_name_fr='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_fr='Dalasi gambien',cu_sub_name_fr='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_fr='franc guinéen',cu_sub_name_fr='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_fr='Quetzal guatémaltèque',cu_sub_name_fr='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_fr='peso de Guinée-Bissau',cu_sub_name_fr='' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_fr='dollar de Guyane',cu_sub_name_fr='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_fr='Dollar hong-kongais',cu_sub_name_fr='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_fr='Lempira hondurien',cu_sub_name_fr='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_fr='Kuna croatien',cu_sub_name_fr='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_fr='Gourde haïtienne',cu_sub_name_fr='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_fr='Forint hongrois',cu_sub_name_fr='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_fr='Roupie indonésienne',cu_sub_name_fr='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_fr='Nouveau shekel israélien',cu_sub_name_fr='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_fr='Roupie indienne',cu_sub_name_fr='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_fr='Dinar irakien',cu_sub_name_fr='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_fr='Rial iranien',cu_sub_name_fr='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_fr='Couronne islandaise',cu_sub_name_fr='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_fr='Dollar jamaïcain',cu_sub_name_fr='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_fr='Dinar jordanien',cu_sub_name_fr='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_fr='Yen japonais',cu_sub_name_fr='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_fr='Shilling kenyan',cu_sub_name_fr='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_fr='Som kirghize',cu_sub_name_fr='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_fr='Riel cambodgien',cu_sub_name_fr='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_fr='Franc comorien',cu_sub_name_fr='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_fr='Won nord-coréen',cu_sub_name_fr='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_fr='Won sud-coréen',cu_sub_name_fr='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_fr='Dinar koweitien',cu_sub_name_fr='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_fr='Dollar des îles Caïmans',cu_sub_name_fr='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_fr='Tenge kazakh',cu_sub_name_fr='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_fr='Kip loatien',cu_sub_name_fr='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_fr='Livre libanaise',cu_sub_name_fr='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_fr='Roupie cinghalaise',cu_sub_name_fr='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_fr='Dollar libérien',cu_sub_name_fr='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_fr='Loti sotho',cu_sub_name_fr='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_fr='Litas lithuanien',cu_sub_name_fr='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_fr='Lats letton',cu_sub_name_fr='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_fr='Dinar libyen',cu_sub_name_fr='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_fr='Dirham marocain',cu_sub_name_fr='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_fr='Leu moldave',cu_sub_name_fr='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_fr='Dinar macédonien',cu_sub_name_fr='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_fr='Kyat du Myanmar',cu_sub_name_fr='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_fr='Togrog',cu_sub_name_fr='möngö' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_fr='Pataca de Macao',cu_sub_name_fr='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_fr='Ouguiya mauritanien',cu_sub_name_fr='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_fr='Lire maltaise',cu_sub_name_fr='' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_fr='Roupie mauricienne',cu_sub_name_fr='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_fr='Roupie maldive',cu_sub_name_fr='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_fr='Kwacha malawite',cu_sub_name_fr='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_fr='Peso mexicain',cu_sub_name_fr='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_fr='Ringgit malais',cu_sub_name_fr='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_fr='Métical mozambicain',cu_sub_name_fr='' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_fr='Dollar namibien',cu_sub_name_fr='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_fr='Naira nigérian',cu_sub_name_fr='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_fr='Cordoba nicaraguayen',cu_sub_name_fr='centime' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_fr='Couronne norvégienne',cu_sub_name_fr='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_fr='Roupie népalaise',cu_sub_name_fr='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_fr='Dollar néo-zélandais',cu_sub_name_fr='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_fr='Rial omanien',cu_sub_name_fr='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_fr='Balboa panaméen',cu_sub_name_fr='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_fr='Nuevo sol péruvien',cu_sub_name_fr='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_fr='Kina papouasien',cu_sub_name_fr='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_fr='Peso philippin',cu_sub_name_fr='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_fr='Roupie pakistanaise',cu_sub_name_fr='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_fr='Złoty polonais',cu_sub_name_fr='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_fr='Guarani paraguayen',cu_sub_name_fr='centime' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_fr='Rial qatari',cu_sub_name_fr='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_fr='Leu roumain',cu_sub_name_fr='' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_fr='Rouble russe',cu_sub_name_fr='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_fr='Franc rwandais',cu_sub_name_fr='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_fr='Ryal saoudien',cu_sub_name_fr='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_fr='Dollar des îles Salomon',cu_sub_name_fr='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_fr='Roupie seychelloise',cu_sub_name_fr='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_fr='Dinar soudanais',cu_sub_name_fr='' WHERE cu_iso_3='SDD';
UPDATE static_currencies SET cu_name_fr='Couronne suédoise',cu_sub_name_fr='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_fr='Dollar singapourien',cu_sub_name_fr='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_fr='Livre de Sainte-Hélène',cu_sub_name_fr='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_fr='Tolar slovène',cu_sub_name_fr='' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_fr='Couronne slovaque',cu_sub_name_fr='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_fr='Leone sierra-léonais',cu_sub_name_fr='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_fr='Shilling somali',cu_sub_name_fr='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_fr='Dobra santoméen',cu_sub_name_fr='centime' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_fr='Colon salvadorien',cu_sub_name_fr='' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_fr='Livre syrienne',cu_sub_name_fr='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_fr='Lilangeni swazi',cu_sub_name_fr='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_fr='baht',cu_sub_name_fr='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_fr='Somoni tadjik',cu_sub_name_fr='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_fr='Manat turkmène',cu_sub_name_fr='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_fr='Dinar tunisien',cu_sub_name_fr='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_fr='Paʻanga tonga',cu_sub_name_fr='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_fr='Dollar de Trinité-et-Tobago',cu_sub_name_fr='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_fr='Dollar taiwanais',cu_sub_name_fr='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_fr='Shilling tanzanien',cu_sub_name_fr='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_fr='Hryvnia ukrainienne',cu_sub_name_fr='' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_fr='Shilling ougandais',cu_sub_name_fr='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_fr='Dollar US',cu_sub_name_fr='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_fr='Peso uruguayen',cu_sub_name_fr='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_fr='Som ouzbek',cu_sub_name_fr='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_fr='Bolivar',cu_sub_name_fr='' WHERE cu_iso_3='VEB';
UPDATE static_currencies SET cu_name_fr='Dồng',cu_sub_name_fr='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_fr='Vatu',cu_sub_name_fr='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_fr='Tala samoan',cu_sub_name_fr='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_fr='Franc CFA (BEAC)',cu_sub_name_fr='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_fr='Dollar de la Caraïbe orientale',cu_sub_name_fr='' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_fr='Franc CFA (BCEAO)',cu_sub_name_fr='' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_fr='Franc pacifique',cu_sub_name_fr='' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_fr='Rial yéménite',cu_sub_name_fr='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_fr='Rand sud-africain',cu_sub_name_fr='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_fr='Kwacha zambien',cu_sub_name_fr='' WHERE cu_iso_3='ZMK';
UPDATE static_currencies SET cu_name_fr='Dollar zimbabwéen',cu_sub_name_fr='' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_fr='Afghani afghan',cu_sub_name_fr='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_fr='Dinar serbe',cu_sub_name_fr='' WHERE cu_iso_3='CSD';
UPDATE static_currencies SET cu_name_fr='Ariary malgache',cu_sub_name_fr='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_fr='Dollar surinamien',cu_sub_name_fr='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_fr='Nouvelle lire turque',cu_sub_name_fr='' WHERE cu_iso_3='TRY';


## static_languages
UPDATE static_languages SET lg_name_fr='Abkhaze' WHERE lg_iso_2='AB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Afar' WHERE lg_iso_2='AA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Afrikaans' WHERE lg_iso_2='AF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Albanais' WHERE lg_iso_2='SQ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Amharique' WHERE lg_iso_2='AM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Arabe' WHERE lg_iso_2='AR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Arménien' WHERE lg_iso_2='HY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Assamais' WHERE lg_iso_2='AS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Aymara' WHERE lg_iso_2='AY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Azéri' WHERE lg_iso_2='AZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Bachkir' WHERE lg_iso_2='BA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Basque' WHERE lg_iso_2='EU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Bengalî' WHERE lg_iso_2='BN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='RDzong-kha' WHERE lg_iso_2='DZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Bihari' WHERE lg_iso_2='BH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Bichlamar' WHERE lg_iso_2='BI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Breton' WHERE lg_iso_2='BR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Bulgare' WHERE lg_iso_2='BG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Birman' WHERE lg_iso_2='MY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Biélorusse' WHERE lg_iso_2='BE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Khmer' WHERE lg_iso_2='KM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Catalan' WHERE lg_iso_2='CA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Zhuang' WHERE lg_iso_2='ZA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Chinois (traditionnel)' WHERE lg_iso_2='ZH' AND lg_country_iso_2='HK';
UPDATE static_languages SET lg_name_fr='Corse' WHERE lg_iso_2='CO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Croate' WHERE lg_iso_2='HR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tchèque' WHERE lg_iso_2='CS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Danois' WHERE lg_iso_2='DA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Néerlandais' WHERE lg_iso_2='NL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Anglais' WHERE lg_iso_2='EN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Espéranto' WHERE lg_iso_2='EO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Estonien' WHERE lg_iso_2='ET' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Féroïen' WHERE lg_iso_2='FO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Persan' WHERE lg_iso_2='FA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Fidjien' WHERE lg_iso_2='FJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Finnois' WHERE lg_iso_2='FI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Français' WHERE lg_iso_2='FR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Frison' WHERE lg_iso_2='FY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Galicien' WHERE lg_iso_2='GL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Gaélique écossais' WHERE lg_iso_2='GD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Mannois' WHERE lg_iso_2='GV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Géorgien' WHERE lg_iso_2='KA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Allemand' WHERE lg_iso_2='DE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Grec' WHERE lg_iso_2='EL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Groenlandais' WHERE lg_iso_2='KL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Guarani' WHERE lg_iso_2='GN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Gujarâtî' WHERE lg_iso_2='GU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Haoussa' WHERE lg_iso_2='HA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Hébreu' WHERE lg_iso_2='HE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Hindi' WHERE lg_iso_2='HI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Hongrois' WHERE lg_iso_2='HU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Islandais' WHERE lg_iso_2='IS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Indonésien' WHERE lg_iso_2='ID' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Inuktitut' WHERE lg_iso_2='IU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Inupiaq' WHERE lg_iso_2='IK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Irlandais' WHERE lg_iso_2='GA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Italien' WHERE lg_iso_2='IT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Japonais' WHERE lg_iso_2='JA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kannada' WHERE lg_iso_2='KN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kâshmîrî' WHERE lg_iso_2='KS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kazakh' WHERE lg_iso_2='KK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kinyarwanda' WHERE lg_iso_2='RW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kirghiz' WHERE lg_iso_2='KY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kirundi' WHERE lg_iso_2='RN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Coréen' WHERE lg_iso_2='KO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kurde' WHERE lg_iso_2='KU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Lao' WHERE lg_iso_2='LO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Letton' WHERE lg_iso_2='LV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Lingala' WHERE lg_iso_2='LN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Lituanien' WHERE lg_iso_2='LT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Macédonien' WHERE lg_iso_2='MK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Malgache' WHERE lg_iso_2='MG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Malais' WHERE lg_iso_2='MS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Malayalam' WHERE lg_iso_2='ML' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Maltais' WHERE lg_iso_2='MT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Maori' WHERE lg_iso_2='MI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Marâthî' WHERE lg_iso_2='MR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Moldave' WHERE lg_iso_2='MO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Mongol' WHERE lg_iso_2='MN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Nauruan' WHERE lg_iso_2='NA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Népalais' WHERE lg_iso_2='NE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Norvégien' WHERE lg_iso_2='NO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Provençal' WHERE lg_iso_2='OC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Oriya' WHERE lg_iso_2='OR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Oromo' WHERE lg_iso_2='OM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Pachto' WHERE lg_iso_2='PS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Polonais' WHERE lg_iso_2='PL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Portugais' WHERE lg_iso_2='PT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Panjâbî' WHERE lg_iso_2='PA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Quechua' WHERE lg_iso_2='QU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Rhéto-roman' WHERE lg_iso_2='RM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Roumain' WHERE lg_iso_2='RO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Russe' WHERE lg_iso_2='RU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Samoan' WHERE lg_iso_2='SM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Sango' WHERE lg_iso_2='SG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Serbe' WHERE lg_iso_2='SR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Sotho du Sud' WHERE lg_iso_2='ST' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Setswana' WHERE lg_iso_2='TN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Shona' WHERE lg_iso_2='SN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Sindhi' WHERE lg_iso_2='SD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Cinghalais' WHERE lg_iso_2='SI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Swati' WHERE lg_iso_2='SS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Slovaque' WHERE lg_iso_2='SK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Slovène' WHERE lg_iso_2='SL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Somali' WHERE lg_iso_2='SO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Espagnol' WHERE lg_iso_2='ES' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Soundanais' WHERE lg_iso_2='SU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Swahili' WHERE lg_iso_2='SW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Suédois' WHERE lg_iso_2='SV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tagalog' WHERE lg_iso_2='TL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tadjik' WHERE lg_iso_2='TG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tamoul' WHERE lg_iso_2='TA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tatar' WHERE lg_iso_2='TT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Télougou' WHERE lg_iso_2='TE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Thaï' WHERE lg_iso_2='TH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tibétain' WHERE lg_iso_2='BO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tigrigna' WHERE lg_iso_2='TI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tongien' WHERE lg_iso_2='TO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tsonga' WHERE lg_iso_2='TS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Turc' WHERE lg_iso_2='TR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Turkmène' WHERE lg_iso_2='TK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Twi' WHERE lg_iso_2='TW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ouïgour' WHERE lg_iso_2='UG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ukrainien' WHERE lg_iso_2='UK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ourdou' WHERE lg_iso_2='UR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ouzbek' WHERE lg_iso_2='UZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Vietnamien' WHERE lg_iso_2='VI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Gallois' WHERE lg_iso_2='CY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Wolof' WHERE lg_iso_2='WO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Xhosa' WHERE lg_iso_2='XH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Yoruba' WHERE lg_iso_2='YO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Zoulou' WHERE lg_iso_2='ZU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Bosniaque' WHERE lg_iso_2='BS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Akan' WHERE lg_iso_2='AK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Aragonais' WHERE lg_iso_2='AN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Avar' WHERE lg_iso_2='AV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Bambara' WHERE lg_iso_2='BM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tchéchène' WHERE lg_iso_2='CE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Chamorro' WHERE lg_iso_2='CH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Cri' WHERE lg_iso_2='CR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tchouvache' WHERE lg_iso_2='CV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Divehi' WHERE lg_iso_2='DV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ewe' WHERE lg_iso_2='EE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Peul' WHERE lg_iso_2='FF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Hiri motu' WHERE lg_iso_2='HO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Créole haïtien' WHERE lg_iso_2='HT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Herero' WHERE lg_iso_2='HZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Igbo' WHERE lg_iso_2='IG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Yi' WHERE lg_iso_2='II' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kikongo' WHERE lg_iso_2='KG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kikuyu' WHERE lg_iso_2='KI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kuanyama' WHERE lg_iso_2='KJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Kanuri' WHERE lg_iso_2='KR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Komi' WHERE lg_iso_2='KV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Cornique' WHERE lg_iso_2='KW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Luxembourgeois' WHERE lg_iso_2='LB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Luganda' WHERE lg_iso_2='LG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Limbourgeois' WHERE lg_iso_2='LI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Luba-Katanga' WHERE lg_iso_2='LU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Marshall' WHERE lg_iso_2='MH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Norvégien bokmål' WHERE lg_iso_2='NB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ndébélé du Nord' WHERE lg_iso_2='ND' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ndonga' WHERE lg_iso_2='NG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Norvégien nynorsk' WHERE lg_iso_2='NN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ndébélé du Sud' WHERE lg_iso_2='NR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Navaho' WHERE lg_iso_2='NV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Chichewa' WHERE lg_iso_2='NY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ojibwa' WHERE lg_iso_2='OJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ossète' WHERE lg_iso_2='OS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Sarde' WHERE lg_iso_2='SC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Sami du Nord' WHERE lg_iso_2='SE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Tahitien' WHERE lg_iso_2='TY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Venda' WHERE lg_iso_2='VE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Wallon' WHERE lg_iso_2='WA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Javanais' WHERE lg_iso_2='JV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Brésilien' WHERE lg_iso_2='PT' AND lg_country_iso_2='BR';
UPDATE static_languages SET lg_name_fr='Chinois (simplifié)' WHERE lg_iso_2='ZH' AND lg_country_iso_2='CN';
UPDATE static_languages SET lg_name_fr='Interlingua' WHERE lg_iso_2='IA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Interlingue' WHERE lg_iso_2='IE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Latin' WHERE lg_iso_2='LA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Sanskrit' WHERE lg_iso_2='SA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Volapük' WHERE lg_iso_2='VO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Yiddish' WHERE lg_iso_2='YI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Avestique' WHERE lg_iso_2='AE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Slavon' WHERE lg_iso_2='CU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Ido' WHERE lg_iso_2='IO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_fr='Pâli' WHERE lg_iso_2='PI' AND lg_country_iso_2='';
