name: Static Analysis

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1' ]
    name: PHPstan
    steps:
      - uses: actions/checkout@v2
      - id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --no-progress
      - run: composer analyse

  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - run: composer install --no-progress
      - run: .Build/bin/phpcs --runtime-set ignore_warnings_on_exit true