name: Tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1' ]
        typo3: [ '^12.4', 'dev-main' ]

    name: PHP ${{ matrix.php }}, TYPO3 ${{ matrix.typo3 }} tests
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Allow composer plugin typo3/cms-composer-installers
        run: composer config --no-plugins allow-plugins.typo3/cms-composer-installers true

      - name: Allow composer plugin typo3/class-alias-loader
        run: composer config --no-plugins allow-plugins.typo3/class-alias-loader true

      - name: Allow composer plugin phpstan/extension-installer
        run: composer config --no-plugins allow-plugins.phpstan/extension-installer true

      - name: Install dependencies with nimut/typo3-complete:${{ matrix.typo3 }}
        if: matrix.typo3 != 'dev-main'
        run: |
          composer require --no-progress "typo3/cms-adminpanel:${{ matrix.typo3 }}" "typo3/cms-backend:${{ matrix.typo3 }}" "typo3/cms-belog:${{ matrix.typo3 }}" "typo3/cms-beuser:${{ matrix.typo3 }}" "typo3/cms-core:${{ matrix.typo3 }}" "typo3/cms-dashboard:${{ matrix.typo3 }}" "typo3/cms-extbase:${{ matrix.typo3 }}" "typo3/cms-extensionmanager:${{ matrix.typo3 }}" "typo3/cms-felogin:${{ matrix.typo3 }}" "typo3/cms-filelist:${{ matrix.typo3 }}" "typo3/cms-filemetadata:${{ matrix.typo3 }}" "typo3/cms-fluid:${{ matrix.typo3 }}" "typo3/cms-fluid-styled-content:${{ matrix.typo3 }}" "typo3/cms-form:${{ matrix.typo3 }}" "typo3/cms-frontend:${{ matrix.typo3 }}" "typo3/cms-impexp:${{ matrix.typo3 }}" "typo3/cms-indexed-search:${{ matrix.typo3 }}" "typo3/cms-info:${{ matrix.typo3 }}" "typo3/cms-install:${{ matrix.typo3 }}" "typo3/cms-linkvalidator:${{ matrix.typo3 }}" "typo3/cms-lowlevel:${{ matrix.typo3 }}" "typo3/cms-opendocs:${{ matrix.typo3 }}" "typo3/cms-reactions:${{ matrix.typo3 }}" "typo3/cms-recycler:${{ matrix.typo3 }}" "typo3/cms-redirects:${{ matrix.typo3 }}" "typo3/cms-reports:${{ matrix.typo3 }}" "typo3/cms-rte-ckeditor:${{ matrix.typo3 }}" "typo3/cms-scheduler:${{ matrix.typo3 }}" "typo3/cms-seo:${{ matrix.typo3 }}" "typo3/cms-setup:${{ matrix.typo3 }}" "typo3/cms-sys-note:${{ matrix.typo3 }}" "typo3/cms-t3editor:${{ matrix.typo3 }}" "typo3/cms-tstemplate:${{ matrix.typo3 }}" "typo3/cms-viewpage:${{ matrix.typo3 }}" "typo3/cms-webhooks:${{ matrix.typo3 }}" "typo3/cms-workspaces:${{ matrix.typo3 }}" "typo3/minimal:^12"
          
          git checkout composer.json

      - name: Install dependencies with nimut/typo3-complete:dev-main and PHP == 8.1
        if: matrix.typo3 == 'dev-main' && matrix.php == '8.1'
        continue-on-error: true
        run: |
          rm -rf composer.lock .Build
          composer require --no-progress "typo3/cms-adminpanel:${{ matrix.typo3 }}" "typo3/cms-backend:${{ matrix.typo3 }}" "typo3/cms-belog:${{ matrix.typo3 }}" "typo3/cms-beuser:${{ matrix.typo3 }}" "typo3/cms-core:${{ matrix.typo3 }}" "typo3/cms-dashboard:${{ matrix.typo3 }}" "typo3/cms-extbase:${{ matrix.typo3 }}" "typo3/cms-extensionmanager:${{ matrix.typo3 }}" "typo3/cms-felogin:${{ matrix.typo3 }}" "typo3/cms-filelist:${{ matrix.typo3 }}" "typo3/cms-filemetadata:${{ matrix.typo3 }}" "typo3/cms-fluid:${{ matrix.typo3 }}" "typo3/cms-fluid-styled-content:${{ matrix.typo3 }}" "typo3/cms-form:${{ matrix.typo3 }}" "typo3/cms-frontend:${{ matrix.typo3 }}" "typo3/cms-impexp:${{ matrix.typo3 }}" "typo3/cms-indexed-search:${{ matrix.typo3 }}" "typo3/cms-info:${{ matrix.typo3 }}" "typo3/cms-install:${{ matrix.typo3 }}" "typo3/cms-linkvalidator:${{ matrix.typo3 }}" "typo3/cms-lowlevel:${{ matrix.typo3 }}" "typo3/cms-opendocs:${{ matrix.typo3 }}" "typo3/cms-reactions:${{ matrix.typo3 }}" "typo3/cms-recycler:${{ matrix.typo3 }}" "typo3/cms-redirects:${{ matrix.typo3 }}" "typo3/cms-reports:${{ matrix.typo3 }}" "typo3/cms-rte-ckeditor:${{ matrix.typo3 }}" "typo3/cms-scheduler:${{ matrix.typo3 }}" "typo3/cms-seo:${{ matrix.typo3 }}" "typo3/cms-setup:${{ matrix.typo3 }}" "typo3/cms-sys-note:${{ matrix.typo3 }}" "typo3/cms-t3editor:${{ matrix.typo3 }}" "typo3/cms-tstemplate:${{ matrix.typo3 }}" "typo3/cms-viewpage:${{ matrix.typo3 }}" "typo3/cms-webhooks:${{ matrix.typo3 }}" "typo3/cms-workspaces:${{ matrix.typo3 }}" "typo3/minimal:${{ matrix.typo3 }}"
          composer require --dev --no-progress saschaegerer/phpstan-typo3:"*" typo3/testing-framework:"*"
          git checkout composer.json

      - name: Code Style
        if: matrix.typo3 != 'dev-main'
        run: .Build/bin/phpcs --runtime-set ignore_warnings_on_exit true

      - name: Code Style for dev-main and PHP == 8.1
        continue-on-error: true
        if: matrix.typo3 == 'dev-main' && matrix.php == '8.1'
        run: .Build/bin/phpcs --runtime-set ignore_warnings_on_exit true

      - name: Unit tests
        run: .Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit

      - name: Functional tests with mariadb
        run: .Build/Scripts/runTests.sh -p ${{ matrix.php }} -d mariadb -s functional

      - name: Functional tests with postgres
        run: .Build/Scripts/runTests.sh -p ${{ matrix.php }} -d postgres -s functional

      - name: Functional tests with sqlite
        run: .Build/Scripts/runTests.sh -p ${{ matrix.php }} -d sqlite -s functional
